import "../styles/modern_normalize.css";
import "../styles/style.css";
import "../styles/utils.css";
import "../styles/components/header.css";
import "../styles/components/introduction.css";
import "../styles/components/events.css";
import "../styles/components/deities.css";
import "../styles/components/officials.css";
import "../styles/components/contact.css";
